name: satellite_nso
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - gdal
  - jupyterlab
  - pip:
      - affine
      - attrs
      - charset-normalizer
      - click
      - click-plugins
      - cligj
      - contourpy
      - cycler
      - earthpy
      - fonttools
      - imageio
      - lazy-loader
      - networkx
      - objectpath
      - pyogrio
      - pyparsing
      - python-dotenv
      - satellite-images-nso
      - scikit-image
      - tqdm
      - numpy
      - pandas
      - matplotlib
      - scikit-learn
      - requests
      - geopandas
      - folium
      - rasterio
      - shapely
      - scipy
      - pillow
      - fiona
      - pyproj
      - jupytext
      - flask
      - flask-cors
      - pillow
      - openpyxl
